name: Basic ActionsGuard Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run ActionsGuard
        uses: cybrking/actions-guard@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name: ${{ github.repository }}

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: reports/
