name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  self-scan:
    name: Self-Scan with ActionsGuard
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Go (for Scorecard)
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Scorecard
        run: go install github.com/ossf/scorecard/v4/cmd/scorecard@latest

      - name: Install ActionsGuard
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run ActionsGuard scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          actionsguard scan --repo ${{ github.repository }} --output ./reports --format html,json,markdown

      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/

      - name: Comment on issues if critical
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔴 Critical Security Issues Found',
              body: 'ActionsGuard detected critical security issues in GitHub Actions workflows. Please review the scan reports.',
              labels: ['security', 'critical']
            })
